#!/usr/bin/env python3
# Copyright 2025 Ira Cooper <ira@wakeful.net>
# SPDX-License-Identifier: GPL-2.0-or-later

"""
Generate sval_config.h from sval.json.

Reads the 'sval' object from sval.json and generates C #defines
for each feature's entry count and enable flag.

Also extracts fragment instance count from composition.instances if present.

Features not present in the JSON will not have defines generated,
allowing code to be excluded via #ifdef at compile time.
"""

import sys
import os
import json

# Map JSON keys to C define names
FEATURE_MAP = {
    'tap_dance': 'TAP_DANCE',
    'combo': 'COMBO',
    'key_override': 'KEY_OVERRIDE',
    'alt_repeat_key': 'ALT_REPEAT_KEY',
    'leader': 'LEADER',
}

# Map features to QMK enable flags (for rules.mk output)
QMK_ENABLE_MAP = {
    'tap_dance': 'TAP_DANCE_ENABLE',
    'combo': 'COMBO_ENABLE',
    'key_override': 'KEY_OVERRIDE_ENABLE',
    'leader': 'LEADER_ENABLE',
}


def generate_config(json_path, header_path, mk_path=None):
    """Generate sval_config.h from sval.json."""

    # Read JSON
    with open(json_path, 'r') as f:
        data = json.load(f)

    sval = data.get('sval', {})

    # Generate C header
    with open(header_path, 'w') as f:
        f.write("// Auto-generated by sval_config.py - DO NOT EDIT\n")
        f.write("// Copyright 2025 Ira Cooper <ira@wakeful.net>\n")
        f.write("// SPDX-License-Identifier: GPL-2.0-or-later\n\n")
        f.write("#pragma once\n\n")

        if not sval:
            f.write("// No sval configuration found in sval.json\n")
        else:
            for json_key, c_name in FEATURE_MAP.items():
                if json_key in sval:
                    count = sval[json_key]
                    f.write(f"#define SVAL_{c_name}_ENTRIES {count}\n")
                    f.write(f"#define SVAL_{c_name}_ENABLE 1\n\n")

        # Extract fragment instance count from composition.instances
        composition = data.get('composition', {})
        instances = composition.get('instances', [])
        if instances:
            f.write(f"// Fragment composition\n")
            f.write(f"#define SVAL_FRAGMENT_INSTANCE_COUNT {len(instances)}\n\n")

    # Generate make fragment if requested
    if mk_path:
        with open(mk_path, 'w') as f:
            f.write("# Auto-generated by sval_config.py - DO NOT EDIT\n\n")
            for json_key, qmk_flag in QMK_ENABLE_MAP.items():
                if json_key in sval:
                    f.write(f"{qmk_flag} = yes\n")

    features = [k for k in FEATURE_MAP.keys() if k in sval]
    print(f"Generated sval config with features: {', '.join(features) if features else 'none'}")
    return True


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <sval.json> <output.h> [output.mk]")
        sys.exit(1)

    json_path = sys.argv[1]
    header_path = sys.argv[2]
    mk_path = sys.argv[3] if len(sys.argv) > 3 else None

    if not os.path.exists(json_path):
        # No sval.json - generate empty config
        with open(header_path, 'w') as f:
            f.write("// Auto-generated - no sval.json found\n")
            f.write("#pragma once\n\n")
            f.write("// No sval features enabled\n")
        if mk_path:
            with open(mk_path, 'w') as f:
                f.write("# Auto-generated - no sval.json found\n")
        print(f"No sval.json found at {json_path}, generated empty config")
        sys.exit(0)

    if not generate_config(json_path, header_path, mk_path):
        sys.exit(1)


if __name__ == '__main__':
    main()
